apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  PORT: "3000"
  DB_USER: "flask_user"
  DB_PASSWORD: "password"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "flask_tasks"
