apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo
    release: prometheus
spec:
  selector:
    app: todo
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort

