#todo-api-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
